### ISSUE TITLE
requirements.txt xmltodict/sqlalchemy 

### ISSUE THREAD

**Issue by raavioli** [snithish/tpc-di_benchmark#1]
Hi, 

great work !

Build was failing and there is an issue with `xmltodict/sqlalchemy` python package 

i have made changes to the docker compose yml file to have requirements.txt under webserver, scheduler and worker.

```yaml

volumes:
      - ./dags:/usr/local/airflow/dags
      - ./requirements.txt:/requirements.txt
    
```

Added requirements.txt to the base folder `.\tpc_di_benchmark` and included

```txt
xmltodict
SQLAlchemy==1.3.15
```

Great work on modelling if you interested in implementing this same using Data Vault Modelling and extending it with Presto for MPP OLAP star schemas using (Kafka:Flink)/Spark  , let me know would love to collaborate.

**Comment by snithish** [comment]
Hi @RaviHindocha 
Thank for bringing up this issue..
I'd happy to review and merge a PR if you are up for it..

>  Great work on modelling if you interested in implementing this same using Data Vault Modelling and extending it with Presto for MPP OLAP star schemas using (Kafka:Flink)/Spark , let me know would love to collaborate.

I am afraid I don't have the bandwidth to dedicate a lot of time on this, but happy to collaborate review PRs and integrate with this repo :)

**Comment by raavioli** [comment]
@snithish sure i dont mind updating to get the image working. will fork out and send it out for review soon.

any pointers on the datagen shell scripts, have doubt whether it's been automated.

wrt
>I am afraid I don't have the bandwidth to dedicate a lot of time on this, but happy to collaborate review PRs and integrate with this repo :)

i understand if its not your priority, i usually have weekends and thats where i plan to dedicate some time, with more people and a better project plan work gets distributed and have more robust output following best practices.
